name: Publish
on:
  push:
    tags:
      - "v*.*.*"

permissions:
  # Grant the ability to checkout the repository
  contents: write
  # Grant the ability to push packages
  packages: write

jobs:
  publish-docker-images:
    name: Push Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Docker images
        run: |
          docker build -t ghcr.io/smithy-security/smithy/pkg/detect-repo-languages ./detect-repo-languages/
          docker push ghcr.io/smithy-security/smithy/pkg/detect-repo-languages
          
